apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: mysql-1
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    run: mysql-1
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: mysql-1
  name: mysql-1
spec:
  replicas: 1
  selector:
    matchLabels:
      run: mysql-1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: mysql-1
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        image: mysql:5.7.19
        name: mysql-1
        ports:
        - containerPort: 3306
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-data
      volumes:
      - name: mysql-data
        hostPath:
          path: /data/mysql