apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: wordpress-1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: wordpress-1
status:
  loadBalancer: {}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: wordpress-1
  name: wordpress-1
spec:
  replicas: 1
  selector:
    matchLabels:
      run: wordpress-1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: wordpress-1
    spec:
      containers:
      - env:
        - name: WORDPRESS_TABLE_PREFIX
          value: wordpress_1
        - name: WORDPRESS_DB_HOST
          value: mysql-1
        - name: WORDPRESS_DB_USER
          value: root
        - name: WORDPRESS_DB_PASSWORD
          value: root
        # dont use this preset on production
        image: wordpress:4.8.1-php5.6-apache
        name: wordpress-1
        ports:
        - containerPort: 80
        resources: {}