---
- name: kubeadm init
  shell: kubeadm init --skip-preflight-checks --pod-network-cidr=10.244.0.0/16

- name: mkdir .kube dir
  file:
    path: /home/ubuntu/.kube/
    state: directory

- name: copy kubeconfig
  copy:
    remote_src: yes
    src: /etc/kubernetes/admin.conf
    dest: /home/ubuntu/.kube/config
    owner: ubuntu
    group: ubuntu

- name: install a pod network (Flanel in this case)
  shell: |
    kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml \
    && kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel-rbac.yml
  environment:
    KUBECONFIG: /home/ubuntu/.kube/config

- name: register token
  shell: kubeadm token list | tail -n 1 | awk '{print $1}'
  register: kube_token

- name: set token fact
  set_fact:
    kube_token: "{{ kube_token['stdout'] }}"